package com.anto426.dynamicisland.ui.theme.themes

import androidx.compose.material3.ColorScheme
import androidx.compose.ui.graphics.Color

val black_surfaceContainerHighest: Color = Color(0xFF36343B)
val black_surfaceContainerHigh: Color = Color(0xFF2B2930)
val black_surfaceContainer: Color = Color(0xFF211F26)
val black_surfaceDim: Color = Color(0xFF141218)
val black_surfaceBright: Color = Color(0xFF3B383E)
val black_surfaceContainerLow: Color = Color(0xFF1D1B22)
val black_surfaceContainerLowest: Color = Color(0xFF0F0D13)
val black_primaryFixed: Color = Color(0xFFEADDFF)
val black_primaryFixedDim: Color = Color(0xFFD0BCFF)
val black_onPrimaryFixed: Color = Color(0xFF21005D)
val black_onPrimaryFixedVariant: Color = Color(0xFF4F378B)
val black_secondaryFixed: Color = Color(0xFFE8DEF8)
val black_secondaryFixedDim: Color = Color(0xFFCCC2DC)
val black_onSecondaryFixed: Color = Color(0xFF1D192B)
val black_onSecondaryFixedVariant: Color = Color(0xFF4A4458)
val black_tertiaryFixed: Color = Color(0xFFFFD8E4)
val black_tertiaryFixedDim: Color = Color(0xFFEFB8C8)
val black_onTertiaryFixed: Color = Color(0xFF31111D)
val black_onTertiaryFixedVariant: Color = Color(0xFF633B48)
val md_theme_black_primary = Color(0xFFE1E3E3)
val md_theme_black_onPrimary = Color(0xFF191C1D)
val md_theme_black_primaryContainer = Color(0xFF191C1D)
val md_theme_black_onPrimaryContainer = Color(0xFFEADDFF)
val md_theme_black_secondary = Color(0xFFCCC2DC)
val md_theme_black_onSecondary = Color(0xFF332D41)
val md_theme_black_secondaryContainer = Color(0xFF4A4458)
val md_theme_black_onSecondaryContainer = Color(0xFFE8DEF8)
val md_theme_black_tertiary = Color(0xFFEFB8C8)
val md_theme_black_onTertiary = Color(0xFF492532)
val md_theme_black_tertiaryContainer = Color(0xFF633B48)
val md_theme_black_onTertiaryContainer = Color(0xFFFFD8E4)
val md_theme_black_error = Color(0xFFF2B8B5)
val md_theme_black_onError = Color(0xFF601410)
val md_theme_black_errorContainer = Color(0xFF8C1D18)
val md_theme_black_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_black_outline = Color(0xFF938F99)
val md_theme_black_background = Color(0xFF000000)
val md_theme_black_onBackground = Color(0xFFE6E1E5)
val md_theme_black_surface = Color(0xFF000000)
val md_theme_black_onSurface = Color(0xFFE6E1E5)
val md_theme_black_surfaceVariant = Color(0xFF49454F)
val md_theme_black_onSurfaceVariant = Color(0xFFCAC4D0)
val md_theme_black_inverseSurface = Color(0xFFE6E1E5)
val md_theme_black_inverseOnSurface = Color(0xFF313033)
val md_theme_black_inversePrimary = Color(0xFF6750A4)
val md_theme_black_shadow = Color(0xFF000000)
val md_theme_black_surfaceTint = Color(0xFFD0BCFF)
val md_theme_black_outlineVariant = Color(0xFF49454F)
val md_theme_black_scrim = Color(0xFF000000)


val black_seed = Color(0xFF6750A4)

val BlackTheme = ColorScheme(
	primary = md_theme_black_primary,
	onPrimary = md_theme_black_onPrimary,
	primaryContainer = md_theme_black_primaryContainer,
	onPrimaryContainer = md_theme_black_onPrimaryContainer,
	inversePrimary = md_theme_black_inversePrimary,
	secondary = md_theme_black_secondary,
	onSecondary = md_theme_black_onSecondary,
	secondaryContainer = md_theme_black_secondaryContainer,
	onSecondaryContainer = md_theme_black_onSecondaryContainer,
	tertiary = md_theme_black_tertiary,
	onTertiary = md_theme_black_onTertiary,
	tertiaryContainer = md_theme_black_tertiaryContainer,
	onTertiaryContainer = md_theme_black_onTertiaryContainer,
	background = md_theme_black_background,
	onBackground = md_theme_black_onBackground,
	surface = md_theme_black_surface,
	onSurface = md_theme_black_onSurface,
	surfaceVariant = md_theme_black_surfaceVariant,
	onSurfaceVariant = md_theme_black_onSurfaceVariant,
	surfaceTint = md_theme_black_surfaceTint,
	inverseSurface = md_theme_black_inverseSurface,
	inverseOnSurface = md_theme_black_inverseOnSurface,
	error = md_theme_black_error,
	onError = md_theme_black_onError,
	errorContainer = md_theme_black_errorContainer,
	onErrorContainer = md_theme_black_onErrorContainer,
	outline = md_theme_black_outline,
	outlineVariant = md_theme_black_outlineVariant,
	scrim = md_theme_black_scrim,
	surfaceBright = black_surfaceBright,
	surfaceDim = black_surfaceDim,
	surfaceContainer = black_surfaceContainer,
	surfaceContainerHigh = black_surfaceContainerHigh,
	surfaceContainerHighest = black_surfaceContainerHighest,
	surfaceContainerLow = black_surfaceContainerLow,
	surfaceContainerLowest = black_surfaceContainerLowest,
	primaryFixed = black_primaryFixed,
	primaryFixedDim = black_primaryFixedDim,
	onPrimaryFixed = black_onPrimaryFixed,
	onPrimaryFixedVariant = black_onPrimaryFixedVariant,
	secondaryFixed = black_secondaryFixed,
	secondaryFixedDim = black_secondaryFixedDim,
	onSecondaryFixed = black_onSecondaryFixed,
	onSecondaryFixedVariant = black_onSecondaryFixedVariant,
	tertiaryFixed = black_tertiaryFixed,
	tertiaryFixedDim = black_tertiaryFixedDim,
	onTertiaryFixed = black_onTertiaryFixed,
	onTertiaryFixedVariant = black_onTertiaryFixedVariant
)